# Generated by Django 3.2.5 on 2021-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='images/'),
        ),
    ]
