# Generated by Django 3.2.5 on 2021-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_employee_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_avatar',
            field=models.ImageField(blank=True, default='/avatar.png', null=True, upload_to='images/'),
        ),
    ]
